name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: E2E CI Tests
        environment:
          name: E2E-CI
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/robertschaedler/oss-test
            azure-pipeline-name: 'E2E Mock Pipeline'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}